# test this file using http://www.yamllint.com/
language: java
sudo: false
script:
    - mvn -v
    - cd nlpCore-app
    - mvn clean install
    - mvn exec:java -Dexec.args="../server/testdata ../server/TestOut.json 10 20"
